在pandas中有两类非常重要的数据结构，即序列Series和数据框DataFrame。

Series类似于numpy中的一维数组，除了通吃一维数组可用的函数或方法，而且其可通过索引标签的方式获取数据，还具有索引的自动对齐功能

Series的创建
序列的创建主要有三种方式： 
1）通过一维数组创建序列
2）通过字典的方式创建序列
3）通过DataFrame中的某一行或某一列创建序列

In [5]:
import numpy as np,pandas as pd
arr1 = np.arange(10)
print(arr1)
print(type(arr1))
s1 = pd.Series(arr1)
print(s1,type(s1))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32 <class 'pandas.core.series.Series'>


In [9]:
dic1 = {'a':10,'b':20,'c':30,'d':40,'e':50}
print(dic1)
print(type(dic1))
s2 = pd.Series(dic1)
print(s2)
print(type(s2))

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
<class 'dict'>
a    10
b    20
c    30
d    40
e    50
dtype: int64
<class 'pandas.core.series.Series'>


DataFrame类似于numpy中的二维数组，同样可以通用numpy数组的函数和方法，而且还具有其他灵活应用，后续会介绍到
DataFrame的创建

DataFrame的创建
1）通过二维数组创建数据框
2）通过字典的方式创建数据框
3）通过数据框的方式创建数据框

In [12]:
arr2 = np.array(np.arange(12).reshape(4,3))
print(arr2,type(arr2))
df1 = pd.DataFrame(arr2)
print(df1,type(df1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] <class 'numpy.ndarray'>
   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11 <class 'pandas.core.frame.DataFrame'>


In [14]:
dic2 = {'a':[1,2,3,4],'b':[5,6,7,8],'c':[9,10,11,12],'d':[13,14,15,16]}
print(dic2,type(dic2))
df2 = pd.DataFrame(dic2)
print(df2,type(df2))

{'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8], 'c': [9, 10, 11, 12], 'd': [13, 14, 15, 16]} <class 'dict'>
   a  b   c   d
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16 <class 'pandas.core.frame.DataFrame'>


In [16]:
print("嵌套字典得方式建立DF")
dic3 = {'one':{'a':1,'b':2,'c':3,'d':4},'two':{'a':5,'b':6,'c':7,'d':8},'three':{'a':9,'b':10,'c':11,'d':12}}
print(dic3,"\n",type(dic3))
df3 = pd.DataFrame(dic3)
print(df3,"\n",type(df3))

嵌套字典得方式建立DF
{'one': {'a': 1, 'b': 2, 'c': 3, 'd': 4}, 'two': {'a': 5, 'b': 6, 'c': 7, 'd': 8}, 'three': {'a': 9, 'b': 10, 'c': 11, 'd': 12}} 
 <class 'dict'>
   one  two  three
a    1    5      9
b    2    6     10
c    3    7     11
d    4    8     12 
 <class 'pandas.core.frame.DataFrame'>


In [17]:
print("数据框方式建立数据框")
df4 = df3[['one','three']]
print(df4)

数据框方式建立数据框
   one  three
a    1      9
b    2     10
c    3     11
d    4     12
