1.创建数组最简单的办法就是使用array函数
2.嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组
3.除非特别说明（稍后将会详细介绍），np.array会尝试为新建的这个数组推断出一个较为合适的数据类型。数据类型保存在一个特殊的dtype对象中。

In [4]:
import numpy as np
data1 = [1,2,3,4,5,6]
arry1 = np.array(data1)
print(arry1)
print(arry1.shape,arry1.dtype)
data2 = [[1,2,3],[4,5,6],[7,8,9]]
arry2 = np.array(data2)
print(arry2)
print(arry2.shape,arry2.dtype)
data3 = [[1.2,1,2.1],[2.3,4.5,5.6]]
arry3 = np.array(data3)
print(arry3)
print(arry3.shape,arry3.dtype)

[1 2 3 4 5 6]
(6,) int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3) int32
[[1.2 1.  2.1]
 [2.3 4.5 5.6]]
(2, 3) float64


除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可

注意：认为np.empty会返回全0数组的想法是不安全的。很多情况下（如前所示），它返回的都是一些未初始化的垃圾值。
empty, empty_like 说明更正： 分配内存空间产生随机值，不进行初始化

In [12]:
# 创建0数组
data_zero = np.zeros(10)
print(data_zero,data_zero.shape,data_zero.dtype,end="\n")
print(np.zeros((3,6)))
# 创建全1矩阵
data_one = np.ones((3,6))
print(data_one)
#np.eye创建单位矩阵，但是创建的是方阵！！！
data_eye = np.eye(4)
print(data_eye)
# 特殊有的·empty
data_empty = np.empty((2,2))
print(data_empty)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,) float64
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1.]
 [1. 1.]]


arange是Python内置函数range的数组版

In [15]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype：
整数被转换成了浮点数。如果将浮点数转换成整数，则小数部分将会被截取删除：

In [22]:
arry = np.array([1,2,3,4])
print(arry.dtype)
float_arry = arry.astype(np.float64)
print(float_arry,"\n",float_arry.dtype)
arry2 = np.array([1.290,3.234,4.4555,6.7978])
int_arry = arry2.astype(np.int64)
print(arry2)
print(int_arry,"\n////*////\n",int_arry.dtype)

int32
[1. 2. 3. 4.] 
 float64
[1.29   3.234  4.4555 6.7978]
[1 3 4 6] 
////*////
 int64


如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式
使用numpy.string_类型时，一定要小心，因为NumPy的字符串数据是大小固定的，发生截取时，不会发出警告。pandas提供了更多非数值数据的便利的处理方法。

In [25]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


 NumPy数组的运算
 数组与标量的算术运算会将标量值传播到各个元素

In [31]:
arry4 = np.array([[1,2,3],[4,5,6]])
print(arry4)
print(arry4 * arry4)
print(arry4 * 2)
print(1 / arry4)
print(arry4 ** 2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1  4  9]
 [16 25 36]]


相同大小的数组进行比较会返回bool数组

In [33]:
arry5 = np.array([1,2,3])
arry6 = np.array([2,2,2])
print(arry5 > arry6)

[False False  True]


In [34]:
 数组的广播
如果两个数组的维数不相同，则元素到元素的操作是不可能的。 然而，在 NumPy 中仍然可以对形状不相似的数组进行操作，因为它拥有广播功能。 较小的数组会广播到较大数组的大小，以便使它们的形状可兼容。

如果满足以下规则，可以进行广播：

    ndim较小的数组会在前面追加一个长度为 1 的维度。
    输出数组的每个维度的大小是输入数组该维度大小的最大值。
    如果输入在每个维度中的大小与输出大小匹配，或其值正好为 1，则可以在计算中使用该输入。
    如果输入的某个维度大小为 1，则该维度中的第一个数据元素将用于该维度的所有计算。

如果上述规则产生有效结果，并且满足以下条件之一，那么数组被称为可广播的。

    数组拥有相同形状。
    数组拥有相同的维数，每个维度拥有相同长度，或者长度为 1。
    数组拥有极少的维度，可以在其前面追加长度为 1 的维度，使上述条件成立。


SyntaxError: invalid character in identifier (<ipython-input-34-cc4fc0d1522f>, line 2)

In [39]:
arry7 = np.array([[1,2,3],[1,2,3],[0,0,0]])
arry8 = np.array([1,1,2])
print("第一个数组：",arry7,"\n第二个数组：",arry8)
print("两个数组相加：")
print(arry7+arry8)

第一个数组： [[1 2 3]
 [1 2 3]
 [0 0 0]] 
第二个数组： [1 1 2]
两个数组相加：
[[2 3 5]
 [2 3 5]
 [1 1 2]]


基本的索引和切片
当你将一个标量值赋值给一个切片时（如arr[5:8]=12），该值会自动传播到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上
“只有冒号”表示选取整个轴，因此你可以像下面这样只对高维轴进行切片
[]是左闭右开的原则

In [78]:
arry9 = np.array([[[1,2,3],[2,3,4]],[[1,1,1],[2,2,2]]])
print("原数组：",arry9)
print("切片数组【1：2】：\n",arry9[1:2])
arry10 = arry9[1:2]
arry10[:] = 0
print("切片数组修改为0：",arry10)
print("修改会传递到原数组中：\n",arry9)
print("切片索引[0,1,1],会选取第一个维度的0，第二个维度的1，第三个维度的1：\n")
print(arry9[0,1,1])
print("一次传入多个切片[:1,2:]")
print(arry9[:1,0:,1:])

原数组： [[[1 2 3]
  [2 3 4]]

 [[1 1 1]
  [2 2 2]]]
切片数组【1：2】：
 [[[1 1 1]
  [2 2 2]]]
切片数组修改为0： [[[0 0 0]
  [0 0 0]]]
修改会传递到原数组中：
 [[[1 2 3]
  [2 3 4]]

 [[0 0 0]
  [0 0 0]]]
切片索引[0,1,1],会选取第一个维度的0，第二个维度的1，第三个维度的1：

3
一次传入多个切片[:1,2:]
[[[2 3]
  [3 4]]]


花式索引：它指的是利用整数数组进行索引
为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可
！！！！花式索引跟切片不一样，它总是将数据复制到新数组中!!!!!

In [82]:
arry10 = np.empty((8,4))
for i in range(8):
    arry10[i] = i
print(arry10)
print("打印arry10[2,4,6,0]:\n",arry10[[2,4,6,0]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
打印arry10[2,4,6,0]:
 [[2. 2. 2. 2.]
 [4. 4. 4. 4.]
 [6. 6. 6. 6.]
 [0. 0. 0. 0.]]
