数组转置和轴对换
转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）

In [4]:
import numpy as np
arry0 = np.arange(15).reshape(3,5)
print(arry0)
print("数组转置：\n")
print(arry0.T)
print("利用np.dot计算矩阵的内积:")
print(np.dot(arry0.T,arry0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
数组转置：

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
利用np.dot计算矩阵的内积:
[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


In [5]:
对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置（比较费脑子）

SyntaxError: invalid character in identifier (<ipython-input-5-7458c92ad013>, line 1)

In [10]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr,arr.shape)
print('==========分割线==============')
print(arr.transpose((1, 0, 2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)
==========分割线==============
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
