用于数组的文件输入输出

NumPy能够读写磁盘上的文本数据或二进制数据。

np.save和np.load是读写磁盘数组数据的两个主要函数。默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为.npy的文件中的：

In [4]:
arr = np.arange(10)
np.save('some_array', arr)
print(np.load('some_array.npy'))

[0 1 2 3 4 5 6 7 8 9]


通过np.savez可以将多个数组保存到一个未压缩文件中，将数组以关键字参数的形式传入即可

In [8]:
arr1 = np.arange(10,20)
np.savez('array_archive.npz', a=arr, b=arr1)
arch = np.load('array_archive.npz')
print(arch['a'])
print(arch['b'])


[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


如果要将数据压缩，可以使用numpy.savez_compressed：

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr1)