线性代数（如矩阵乘法、矩阵分解、行列式以及其他方阵数学等）是任何数组库的重要组成部分。不像某些语言（如MATLAB），通过*对两个二维数组相乘得到的是一个元素级的积，而不是一个矩阵点积。因此，NumPy提供了一个用于矩阵乘法的dot函数（既是一个数组方法也是numpy命名空间中的一个函数）：
@符（类似Python 3.5）也可以用作中缀运算符，进行矩阵乘法

In [5]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))
print("@符（类似Python 3.5）也可以用作中缀运算符，进行矩阵乘法")
print(np.ones(3))
print(x @ np.ones(3))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]
[[ 28.  64.]
 [ 67. 181.]]
@符（类似Python 3.5）也可以用作中缀运算符，进行矩阵乘法
[1. 1. 1.]
[ 6. 15.]


numpy.linalg中有一组标准的矩阵分解运算以及诸如求逆和行列式之类的东西。它们跟MATLAB和R等语言所使用的是相同的行业标准线性代数库，如BLAS、LAPACK、Intel MKL（Math Kernel Library，可能有，取决于你的NumPy版本）等

diag         以一维数组的形式返回仿真对角线(或非对角线元素),或将一维数组转为方阵(非对角元素为0)
dot          矩阵乘法
trace        计算对角线元素的和
det          计算矩阵行列式
eig          计算方阵的本征值和本征向量
inv          计算方阵的逆
pinv         计算矩阵的Moore-Preose伪逆
qr           计算QR分解
svd          计算奇异值分解
solve        解线性方程组Ax=b,其中A为一个方阵
lstsq        计算Ax=b的最小二乘解